name = "DerivedCategories"
uuid = "a6f9c7b2-6273-4b59-9f0d-595f15538316"
authors = [
	"Kamal Saleh <kamal.saleh@uni-siegen.de>"
]

# Transpiled from GAP's DerivedCategories v2026.07-03
version = "0.1.1"

[deps]
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
SubcategoriesForCAP = "54e686c7-8599-4fba-8d83-06e8ab9e4db3"
LinearAlgebraForCAP = "3dc4824f-14ac-4ab7-8a60-75dbcd4a9d60"
FpCategories = "b9f20f1b-1226-4811-b6a0-b2e47a225553"
FpLinearCategories = "607c1b85-d155-426e-91c9-9defd76aa9e1"
LinearClosuresForCAP = "1f080b7b-ff6a-46b3-9ade-986f655adc86"
AdditiveClosuresForCAP = "bbee75d5-3cb4-4478-8ae7-eddc7864e69e"
FreydCategoriesForCAP = "cec356e3-7627-4f73-8308-af32cbf46c2b"
PresheafCategories = "7356a560-9b13-4027-8f83-9f0b8f55db70"
FunctorCategories = "019ed0a3-ec8b-7b2c-b938-de216bf4c7f6"
TriangulatedCategories = "7529282d-5a2e-4f9e-a096-9460618321a6"
ComplexesCategories = "25740295-7925-405d-8250-6795ea33aeec"
HomotopyCategories = "f0c53ac8-2cb1-47b4-9ede-2340aeeefb7b"

[weakdeps]

[extensions]

[compat]
MatricesForHomalg = "~0.1.9"
CAP = "~0.8.10"
SubcategoriesForCAP = "~0.1.3"
LinearAlgebraForCAP = "~0.2.3"
HomotopyCategories = "~0.1.0"
FpCategories = "~0.1.13"
FpLinearCategories = "~0.2.4"
LinearClosuresForCAP = "~0.2.3"
AdditiveClosuresForCAP = "~0.2.4"
FreydCategoriesForCAP = "~0.2.4"
FunctorCategories = "~0.1.0"
PresheafCategories = "~0.1.5"
TriangulatedCategories = "~0.1.0"
ComplexesCategories = "~0.1.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
